# ===============================
# = Active profile set
# ===============================
#spring.profiles.active=development
#spring.profiles.active=staging
#spring.profiles.active=production

# Maven commands: 
# - mvn spring-boot:run -Dspring-boot.run.profiles=development
# - mvn spring-boot:run -Dspring-boot.run.profiles=staging
# - mvn spring-boot:run -Dspring-boot.run.profiles=production

spring.profiles.active=@activatedProperties@

# Banner configurations
spring.banner.location=classpath:./banners/adailsilva-banner.txt
#spring.banner.image.location=classpath:banner-adailsilva.gif
#spring.banner.image.width=  // TODO
#spring.banner.image.height= // TODO
#spring.banner.image.margin= // TODO
#spring.banner.image.invert= // TODO

spring.application.name=ChirpStack Consumer
spring.application.version=1.0.0
