
---

apiVersion: v1
kind: Service
metadata:
  name: udp-1710-app-service
  namespace: oci-devops
  labels:
    app: udp-1710-app-service
spec:
  selector:
    app: udp-app-with-healthcheck-1710-deployment
  # clusterIP: "None"
  type: ClusterIP
  ports:
    - name: "1710-to-1710"
      protocol: UDP
      port: 1710
      targetPort: 1710

# O NLB da OCI irá encaminhar UDP na porta 1710 para o NodePort 30710 nos nodes.
