
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-v4-postgresql-config-map
  namespace: chirpstack-v4
  labels:
    app: chirpstack-v4-postgresql-config-map
data:
  001.init-chirpstack-v4.sh: |

    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE ROLE chirpstack WITH LOGIN PASSWORD 'chirpstack';
        CREATE DATABASE chirpstack WITH OWNER chirpstack;
    EOSQL
  
  002.chirpstack-v4_extensions.sh: |

    #!/bin/bash
    set -e

    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname="chirpstack" <<-EOSQL
        CREATE EXTENSION pg_trgm;
        CREATE EXTENSION hstore;
    EOSQL
