
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: chirpstack-v4-gateway-bridge-config-map
  namespace: chirpstack-v4
  labels:
    app: chirpstack-v4-gateway-bridge-config-map
data:
  chirpstack-gateway-bridge.toml: |
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.

    [integration.mqtt.auth.generic]
    #servers=["tcp://chirpstack-v4-mosquitto-service.chirpstack-v4.svc.cluster.local:1893"]
    servers=["tcp://chirpstack-v4-mosquitto-service.chirpstack-v4.svc.cluster.local:8883"]
    username="adailsilva"
    password="H@cker101"

    [integration.mqtt]
    event_topic_template="au915_1/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
    state_topic_template="au915_1/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
    command_topic_template="au915_1/gateway/{{ .GatewayID }}/command/#"
