FROM nginx:latest

# Metadados da imagem
LABEL maintainer="AdailSilva <adail101@hotmail.com>" \
      app="homepage-nginx" \
      description="K8S – AdailSilva-IoT"

COPY index.html /usr/share/nginx/html/index.html
